SovereignCloudStack/cluster-stack-provider-openstack

- .github/workflows/test.yaml
- .golangci.yml
- Makefile
- cmd/main.go
- hack/version.sh
- internal/controller/openstackclusterstackrelease_controller.go
- internal/controller/openstackclusterstackreleasetemplate_controller.go
- internal/controller/openstacknodeimagerelease_controller.go
remove goconst and goimports from golangci config. This also adds revive
latest config.
Signed-off-by: Anurag <anurag.kumar@syself.com>
> 🌱 remove goconst and goimports

- .github/labeler.yaml
- upgrade of `actions/labeler` via this PR https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/pull/10 from v4 to v5 contains a breaking change where we need to update our config.  
Fixes #
**TODOs**:
> 🌱 update labeler config for v5

- Makefile
- hack/ensure-env-variables.sh
Add missing script to ensure correct env variables
> :sparkles: Add script to ensure correct env variables

- api/v1alpha1/openstackclusterstackrelease_types.go
- config/crd/bases/infrastructure.clusterstack.x-k8s.io_openstackclusterstackreleases.yaml
It was removed when the *Ready* field was introduced
> :sparkles: Add AGE column for openstackclusterstackrelease

- api/v1alpha1/openstacknodeimagerelease_types.go
- internal/controller/openstacknodeimagerelease_controller.go
This reapplies the change discussed in #27  in an updated form. This time `DeepCopyInto` is correctly generated for an aliased type of the upstream `CreateOpts` fixing the build issue found earlier.
**TODOs**:
> :seedling: Reuse existing "images.CreateOpts" for node image releases

- cmd/main.go
- config/rbac/role.yaml
- internal/controller/openstackclusterstackrelease_controller.go
- internal/controller/openstacknodeimagerelease_controller.go
CSPO controllers record multiple events to the resources they manage. However, these events were not recorded in CRs.
Fixes: #47
> :bug: Fix events recording

- cmd/main.go
- internal/controller/suite_test.go
This PR cleans up most basic scaffold traces in the code.
> :seedling: Code cleanup

- Tiltfile
- docs/develop.md
CSPO template now doesn't need reloading
> :bug: Make tilt green on the first run

- internal/controller/openstackclusterstackrelease_controller.go
create github client only if required, based on SovereignCloudStack/cluster-stack-operator#67, and SovereignCloudStack/cluster-stack-operator#70
Fixes #80
**TODOs**:
> :seedling: Create GitHub client only if it is necessary

- .github/labels.yaml
- .github/renovate/commitMessage.json5
- .github/renovate/labels.json5
- .github/workflows/test.yaml
- .gitignore
- Makefile
- README.md
- Tiltfile
- config/cspo/cluster.yaml
- config/cspo/clusterstack.yaml
- docs/develop.md
- local_cso.yaml
- tilt-settings.yaml.example
This PR adds local_mode with cspo. 
This also removes helm from cspo image. (Fixes https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/issues/81)
There are some follow-up task (usage docs) to this which can be added in a separate commit or PR.
> ✨ use local_mode with cspo

- .envrc.sample
- Makefile
Based on the introduction of `local_mode` feature(see issue #76). Some env variables are not needed when we are using local_mode. This commit adjust .envrc.sample and also remove these unnecessary env variables in make target env-vars-for-wl-cluster.
Fixes #100 
**TODOs**:
> :seedling: Remove unnecessary env variables in make target env-vars-for-wl-cluster

- README.md
- Tiltfile
- api/v1alpha1/conditions_const.go
- api/v1alpha1/openstackclusterstackrelease_types.go
- api/v1alpha1/openstacknodeimagerelease_types.go
- config/crd/bases/infrastructure.clusterstack.x-k8s.io_openstackclusterstackreleases.yaml
- config/crd/bases/infrastructure.clusterstack.x-k8s.io_openstackclusterstackreleasetemplates.yaml
- config/crd/bases/infrastructure.clusterstack.x-k8s.io_openstacknodeimagereleases.yaml
- config/cspo/cspotemplate.yaml
- config/cspo/secret.yaml
- examples/cspotemplate.yaml
- internal/controller/openstackclusterstackrelease_controller.go
- internal/controller/openstackclusterstackrelease_controller_test.go
- internal/controller/openstacknodeimagerelease_controller.go
- internal/controller/openstacknodeimagerelease_controller_test.go
- internal/test/integration/github/integration_test.go
- internal/test/integration/openstack/controller_test.go
Add default values for the 'cloudName' and 'identityRef' fields and move `cloudName` to the secret.
Fixes #90 
**TODOs**:
> ⚠️  Add default values for the 'cloudName' and 'identityRef' fields

- internal/controller/openstackclusterstackrelease_controller.go
- internal/controller/openstackclusterstackrelease_controller_test.go
> :sparkles: Add hash mode compatibility

- README.md
Just a README update before release v0.1.0-alpha.2
/test on the latest main of CSPO passed successfully utilizing the CSO `v0.1.0-alpha.3`
> :book: Release CSPO v0.1.0-alpha.2

- Makefile
- Tiltfile
- config/cspo/clusterstack.yaml
- docs/develop.md
- **add make target to apply clusterstack resource**
this commit adds make target related to
clusterstacks to the repo. We want to let tilt
start the controller first and then apply the
clusterstack and openstackclusterstackreleasetemplate
resource via a click on tilt UI.
In creation of resources, we are creating
openstackclusterstackreleasetemplate first followed
by clusterstack resource.
Signed-off-by: kranurag7 <anurag.kumar@syself.com>
> :seedling: add make target to apply clusterstack resource

- internal/controller/openstacknodeimagerelease_controller.go
- internal/controller/openstacknodeimagerelease_controller_test.go
This PR improves image filtering
Fixes #116 
**TODOs**:
> :sparkles: Improve image filtering

- README.md
- Tiltfile
- go.mod
- go.sum
- local_cso.yaml
- tilt-settings.yaml.example
- vendor/modules.txt
this commit udpates to the new release of CSO.
Fixes #
**TODOs**:
> 🌱 update to cso v0.1.0-alpha.5

- .envrc.sample
- .github/workflows/release.yaml
- Makefile
- hack/kind-dev.sh
- images/builder/Dockerfile
- images/cspo/Dockerfile
Fixes https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/issues/128
this commit updates builder images and adds a make target so that we copy the static executables right from the container image. it's fast and we don't have to pull it from the internet again and again if we have the builder image present locally.
- for testing 
```bash
$ docker build -t ghcr.io/sovereigncloudstack/cspo-builder:0.1.0 -f images/builder/Dockerfile images/builder/
```
And then invoke any of the following make targets because these targets depend on the builder image.
```bash
make lint-yaml
make lint-yaml-ci
make lint-links
make lint-dockerfile
make lint-golang
make lint-golang-ci
make format-golang
make generate-modules
```
Here's the output from my machine: …
> ✨ use new builder image approach

- .github/workflows/release.yaml
Fixes GitHub error 403 undefined in release job, see https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/actions/runs/8464068433/job/23188344741
Fixes #137
> 🐛 Fix 403 error in release job

- docs/troubleshooting.md
- internal/controller/openstacknodeimagerelease_controller.go
- internal/controller/openstacknodeimagerelease_controller_test.go
Based on the discussion in matrix chat, see [here](https://matrix.to/#/!NZpJdPGjAHISXnHUil:matrix.org/$b2FJrT-ApeHmVFPXbWZm3ZbK5JoGlNYYIyNwUhM_vXA?via=matrix.org&via=regio.chat&via=matrix.kptt.net). We would like to support a scenario where AuthURL in clouds.yaml is not signed by the public authority like e.g. Let's Encrypt. This can be resolved by specify the CA certificate or adding verify: false into your clouds.yaml file. CAPO already implemented [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/acc680d3659da119475ca47530f6cc67f30b524d/docs/book/src/topics/troubleshooting.md#providerclient-authentication-err).
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> :sparkles: Support specifying the CA cert or adding verify=false into clouds.yaml

- .github/workflows/schedule-update-bot.yaml
add buildx in renovate workflow
renovate workflow failed because we build image in that workflow and
buildx was missing. buildx is now the default builder of docker and we
cannot build images without that.
This commit adds buildx to the renovate workflow so that when renovate
workflow is run and inside the workflow, if we build docker image then
that shouldn't give us any error.
--- 
Ref: https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/pull/161#issuecomment-2109927399
> 🌱 add buildx in renovate workflow

- Makefile
- config/crd/kustomization.yaml
- config/default/kustomization.yaml
- config/localmode/kustomization.yaml
- config/manager/kustomization.yaml
- config/prometheus/kustomization.yaml
- config/rbac/kustomization.yaml
related: https://github.com/SovereignCloudStack/cluster-stack-operator/issues/219
Fixes #
**TODOs**:
> 🌱 update kustomize to v5.4.2 version

- .github/workflows/pr-lint.yaml
- README.md
> :bug:  Apache 2 link leads to failed check

- api/v1alpha1/openstacknodeimagerelease_types.go
- config/crd/bases/infrastructure.clusterstack.x-k8s.io_openstacknodeimagereleases.yaml
- internal/controller/openstacknodeimagerelease_controller_test.go
This PR contains a hot-fix that allows CreateOpts.properties definition via `node-images.yaml` as follows:
```yaml
apiVersion: openstack.infrastructure.clusterstack.x-k8s.io/v1alpha1
openStackNodeImages:
- createOpts:
container_format: bare
disk_format: qcow2
name: ubuntu-capi-image-v1.29.9
visibility: private
properties:
hw_disk_bus: "scsi"
hw_rng_model: "virtio"
hw_scsi_model: "virtio-scsi"
url: ...
```
Fixes #223 
**TODOs**:
> :bug: Fix image properties propagation
